spring.datasource.url=jdbc:${DATABASE_URL}
spring.datasource.username=postgres.iiuasobhlleppzsoyytb
spring.datasource.password=admin123

# JPA & Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server Port
server.port=8080